name: Build MT7981 immortalwrt 18.06

on:
  push:
    branches: 
      - main
    paths:
      - 'MT7981_18.06.config'
  workflow_dispatch:

env:
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash
        # sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo timedatectl set-timezone "$TZ"
    - name: Prepare
      run: |
        # git clone -b mt7981 --single-branch --depth=1 https://github.com/padavanonly/immortalwrtARM immortalwrt
        git clone -b mt7981 --single-branch https://github.com/padavanonly/immortalwrtARM immortalwrt
        cd immortalwrt/
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp ../360T7.config ./.config
    - name: Compile the firmware
      id: compile
      run: |
        cd immortalwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd immortalwrt/bin/targets/*/*
        rm -rf packages
        find . -name "immortalwrt-toolchain-mediatek-mt7981_gcc-8.4.0_musl.Linux-x86_64.tar.bz2" | xargs rm -rf
        find . -name "*initramfs-kernel.bin" | xargs rm -rf
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: MT7981_18.06_immortalwrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        keep_minimum_runs: 3
        delete_workflow_pattern: 'Build MT7981 immortalwrt 18.06'
